<template>
<v-main>
  <v-container fluid class="pa-1 mt-3">
    <!-- <v-card elevation="2" style="background-image: url('../src/assets/images/background2.jpg');  background-size: cover;"> -->
<v-card class="pa-1" elevation="2" style="background-image: linear-gradient(to top right, rgba(19,84,122,.8), rgba(128,208,199,.8)), url('../src/assets/images/background3.jpg'); background-size: cover;">

    <v-card color="grey-lighten-5"
                    border
                    class="mb-2"
                    density="compact">
    <DataTable :dataItems="containersList" :dataItemsHeaders="containersListHeaders" name="CONTAINERS"/>
    <br>
    </v-card>
    <br><br>
    <v-card color="grey-lighten-5"
                    border
                    class="mb-2"
                    density="compact">
    <DataTable :dataItems="employesList" :dataItemsHeaders="employesListHeaders" name="EMPLOYES"/>
    <br>
    </v-card>
    <br><br>
    <v-card color="grey-lighten-5"
                    border
                    density="compact">
    <DataTable :dataItems="dataItems" :dataItemsHeaders="dataItemsHeaders" name="Something third"/>
    <br>
    </v-card>
    </v-card>

  </v-container>
</v-main>
</template>

<script>
import DataTable from '@/components/DataTable.vue'
export default {
  components:{
    DataTable
  },
  data() {
    return{
    containersListHeaders:['id','reference_number','location','country','responsible_name','responsible_email','client_name','transport_type','product_type','last_modify','created_at','View','Action'],
    containersList : [
  {
    id: 1,
    reference_number: '3224301',
    location: 'San Miguel',
    country: 'Bolivia',
    responsible_name: 'Mark',
    responsible_email: 'luka@gmail.com',
    client_name: 'Sin Xaio Hel',
    transport_type: 'Sea',
    product_type: 'Oil',
    last_modify: '07/15/2020',
    created_at: '07/15/2020',
  },
  {
    id: 2,
    reference_number: '5678912',
    location: 'New York',
    country: 'United States',
    responsible_name: 'John',
    responsible_email: 'john@gmail.com',
    client_name: 'ABC Company',
    transport_type: 'Air',
    product_type: 'Electronics',
    last_modify: '09/20/2021',
    created_at: '09/20/2021',
  },
  {
    id: 3,
    reference_number: '9128374',
    location: 'London',
    country: 'United Kingdom',
    responsible_name: 'Emma',
    responsible_email: 'emma@gmail.com',
    client_name: 'XYZ Corporation',
    transport_type: 'Sea',
    product_type: 'Textiles',
    last_modify: '03/10/2022',
    created_at: '03/10/2022',
  },
  {
    id: 4,
    reference_number: '4538291',
    location: 'Paris',
    country: 'France',
    responsible_name: 'Sophie',
    responsible_email: 'sophie@gmail.com',
    client_name: 'ABC Company',
    transport_type: 'Air',
    product_type: 'Perfumes',
    last_modify: '12/05/2021',
    created_at: '12/05/2021',
  },
  {
    id: 5,
    reference_number: '1928374',
    location: 'Sydney',
    country: 'Australia',
    responsible_name: 'Michael',
    responsible_email: 'michael@gmail.com',
    client_name: 'Sin Xaio Hel',
    transport_type: 'Land',
    product_type: 'Furniture',
    last_modify: '08/18/2021',
    created_at: '08/18/2021',
  },
  {
    id: 6,
    reference_number: '8129345',
    location: 'Berlin',
    country: 'Germany',
    responsible_name: 'Thomas',
    responsible_email: 'thomas@gmail.com',
    client_name: 'XYZ Corporation',
    transport_type: 'Sea',
    product_type: 'Clothing',
    last_modify: '01/12/2022',
    created_at: '01/12/2022',
  },
  {
    id: 7,
    reference_number: '7845362',
    location: 'Tokyo',
    country: 'Japan',
    responsible_name: 'Yuki',
    responsible_email: 'yuki@gmail.com',
    client_name: 'ABC Company',
    transport_type: 'Air',
    product_type: 'Electronics',
    last_modify: '06/28/2021',
    created_at: '06/28/2021',
  },
  {
    id: 8,
    reference_number: '1267893',
    location: 'Toronto',
    country: 'Canada',
    responsible_name: 'Emily',
    responsible_email: 'emily@gmail.com',
    client_name: 'XYZ Corporation',
    transport_type: 'Land',
    product_type: 'Food',
    last_modify: '04/02/2022',
    created_at: '04/02/2022',
  },
  {
    id: 9,
    reference_number: '3748291',
    location: 'Madrid',
    country: 'Spain',
    responsible_name: 'Carlos',
    responsible_email: 'carlos@gmail.com',
    client_name: 'Sin Xaio Hel',
    transport_type: 'Air',
    product_type: 'Cosmetics',
    last_modify: '09/15/2021',
    created_at: '09/15/2021',
  },
  {
    id: 10,
    reference_number: '9382712',
    location: 'Rome',
    country: 'Italy',
    responsible_name: 'Giulia',
    responsible_email: 'giulia@gmail.com',
    client_name: 'ABC Company',
    transport_type: 'Sea',
    product_type: 'Luxury Goods',
    last_modify: '11/11/2021',
    created_at: '11/11/2021',
  },
  {
    id: 11,
    reference_number: '5729103',
    location: 'Moscow',
    country: 'Russia',
    responsible_name: 'Ivan',
    responsible_email: 'ivan@gmail.com',
    client_name: 'XYZ Corporation',
    transport_type: 'Land',
    product_type: 'Machinery',
    last_modify: '05/25/2022',
    created_at: '05/25/2022',
  },
  {
    id: 12,
    reference_number: '1827364',
    location: 'Cairo',
    country: 'Egypt',
    responsible_name: 'Fatima',
    responsible_email: 'fatima@gmail.com',
    client_name: 'ABC Company',
    transport_type: 'Air',
    product_type: 'Jewelry',
    last_modify: '12/07/2021',
    created_at: '12/07/2021',
  },
  {
    id: 13,
    reference_number: '3847502',
    location: 'Mumbai',
    country: 'India',
    responsible_name: 'Aarav',
    responsible_email: 'aarav@gmail.com',
    client_name: 'Sin Xaio Hel',
    transport_type: 'Sea',
    product_type: 'Electronics',
    last_modify: '10/02/2022',
    created_at: '10/02/2022',
  },
  {
    id: 14,
    reference_number: '9078561',
    location: 'Rio de Janeiro',
    country: 'Brazil',
    responsible_name: 'Isabella',
    responsible_email: 'isabella@gmail.com',
    client_name: 'XYZ Corporation',
    transport_type: 'Air',
    product_type: 'Sporting Goods',
    last_modify: '07/12/2021',
    created_at: '07/12/2021',
  },
  {
    id: 15,
    reference_number: '1938475',
    location: 'Athens',
    country: 'Greece',
    responsible_name: 'Nikos',
    responsible_email: 'nikos@gmail.com',
    client_name: 'ABC Company',
    transport_type: 'Land',
    product_type: 'Wine',
    last_modify: '09/14/2021',
    created_at: '09/14/2021',
  },
  {
    id: 16,
    reference_number: '6457382',
    location: 'Seoul',
    country: 'South Korea',
    responsible_name: 'Ji-hyun',
    responsible_email: 'ji-hyun@gmail.com',
    client_name: 'Sin Xaio Hel',
    transport_type: 'Sea',
    product_type: 'Clothing',
    last_modify: '08/11/2021',
    created_at: '08/11/2021',
  },
  {
    id: 17,
    reference_number: '2938476',
    location: 'Helsinki',
    country: 'Finland',
    responsible_name: 'Mika',
    responsible_email: 'mika@gmail.com',
    client_name: 'XYZ Corporation',
    transport_type: 'Air',
    product_type: 'Electronics',
    last_modify: '06/26/2021',
    created_at: '06/26/2021',
  },
  {
    id: 18,
    reference_number: '8172634',
    location: 'Stockholm',
    country: 'Sweden',
    responsible_name: 'Emma',
    responsible_email: 'emma@gmail.com',
    client_name: 'ABC Company',
    transport_type: 'Land',
    product_type: 'Furniture',
    last_modify: '03/21/2022',
    created_at: '03/21/2022',
  },
  {
    id: 19,
    reference_number: '3748291',
    location: 'Oslo',
    country: 'Norway',
    responsible_name: 'Olav',
    responsible_email: 'olav@gmail.com',
    client_name: 'Sin Xaio Hel',
    transport_type: 'Sea',
    product_type: 'Food',
    last_modify: '12/08/2021',
    created_at: '12/08/2021',
  },
  {
    id: 20,
    reference_number: '9182735',
    location: 'Vienna',
    country: 'Austria',
    responsible_name: 'Hans',
    responsible_email: 'hans@gmail.com',
    client_name: 'XYZ Corporation',
    transport_type: 'Air',
    product_type: 'Watches',
    last_modify: '10/16/2021',
    created_at: '10/16/2021',
  },
  {
    id: 21,
    reference_number: '2748503',
    location: 'Dubai',
    country: 'United Arab Emirates',
    responsible_name: 'Fatima',
    responsible_email: 'fatima@gmail.com',
    client_name: 'ABC Company',
    transport_type: 'Land',
    product_type: 'Perfumes',
    last_modify: '09/05/2022',
    created_at: '09/05/2022',
  },
  {
    id: 22,
    reference_number: '4938502',
    location: 'Lisbon',
    country: 'Portugal',
    responsible_name: 'Miguel',
    responsible_email: 'miguel@gmail.com',
    client_name: 'Sin Xaio Hel',
    transport_type: 'Sea',
    product_type: 'Textiles',
    last_modify: '07/09/2021',
    created_at: '07/09/2021',
  },
  {
    id: 23,
    reference_number: '7856402',
    location: 'Amsterdam',
    country: 'Netherlands',
    responsible_name: 'Lotte',
    responsible_email: 'lotte@gmail.com',
    client_name: 'XYZ Corporation',
    transport_type: 'Air',
    product_type: 'Electronics',
    last_modify: '11/24/2021',
    created_at: '11/24/2021',
  },
  {
    id: 24,
    reference_number: '1938475',
    location: 'Copenhagen',
    country: 'Denmark',
    responsible_name: 'Erik',
    responsible_email: 'erik@gmail.com',
    client_name: 'ABC Company',
    transport_type: 'Land',
    product_type: 'Furniture',
    last_modify: '07/18/2021',
    created_at: '07/18/2021',
  },
  {
    id: 25,
    reference_number: '7463852',
    location: 'Zurich',
    country: 'Switzerland',
    responsible_name: 'Lena',
    responsible_email: 'lena@gmail.com',
    client_name: 'Sin Xaio Hel',
    transport_type: 'Sea',
    product_type: 'Clothing',
    last_modify: '11/02/2022',
    created_at: '11/02/2022',
  },
  {
    id: 26,
    reference_number: '1029384',
    location: 'Prague',
    country: 'Czech Republic',
    responsible_name: 'Tomas',
    responsible_email: 'tomas@gmail.com',
    client_name: 'XYZ Corporation',
    transport_type: 'Air',
    product_type: 'Cosmetics',
    last_modify: '06/12/2021',
    created_at: '06/12/2021',
  },
  {
    id: 27,
    reference_number: '2918374',
    location: 'Budapest',
    country: 'Hungary',
    responsible_name: 'Adam',
    responsible_email: 'adam@gmail.com',
    client_name: 'ABC Company',
    transport_type: 'Land',
    product_type: 'Wine',
    last_modify: '12/09/2021',
    created_at: '12/09/2021',
  },
  {
    id: 28,
    reference_number: '1039274',
    location: 'Warsaw',
    country: 'Poland',
    responsible_name: 'Kasia',
    responsible_email: 'kasia@gmail.com',
    client_name: 'Sin Xaio Hel',
    transport_type: 'Sea',
    product_type: 'Electronics',
    last_modify: '11/03/2022',
    created_at: '11/03/2022',
  },
  {
    id: 29,
    reference_number: '3748291',
    location: 'Brussels',
    country: 'Belgium',
    responsible_name: 'Sophie',
    responsible_email: 'sophie@gmail.com',
    client_name: 'XYZ Corporation',
    transport_type: 'Air',
    product_type: 'Chocolate',
    last_modify: '04/10/2021',
    created_at: '04/10/2021',
  },
  {
    id: 30,
    reference_number: '9182734',
    location: 'Vienna',
    country: 'Austria',
    responsible_name: 'Johann',
    responsible_email: 'johann@gmail.com',
    client_name: 'ABC Company',
    transport_type: 'Land',
    product_type: 'Artwork',
    last_modify: '06/20/2021',
    created_at: '06/20/2021',
  },
  {
    id: 31,
    reference_number: '8273641',
    location: 'Bucharest',
    country: 'Romania',
    responsible_name: 'Alexandra',
    responsible_email: 'alexandra@gmail.com',
    client_name: 'Sin Xaio Hel',
    transport_type: 'Sea',
    product_type: 'Furniture',
    last_modify: '10/01/2022',
    created_at: '10/01/2022',
  },
  {
    id: 32,
    reference_number: '1029384',
    location: 'Sofia',
    country: 'Bulgaria',
    responsible_name: 'Nikolay',
    responsible_email: 'nikolay@gmail.com',
    client_name: 'XYZ Corporation',
    transport_type: 'Air',
    product_type: 'Perfumes',
    last_modify: '07/29/2021',
    created_at: '07/29/2021',
  },
  {
    id: 33,
    reference_number: '4857392',
    location: 'Dublin',
    country: 'Ireland',
    responsible_name: 'Aoife',
    responsible_email: 'aoife@gmail.com',
    client_name: 'ABC Company',
    transport_type: 'Land',
    product_type: 'Whiskey',
    last_modify: '07/02/2022',
    created_at: '07/02/2022',
  },
  {
    id: 34,
    reference_number: '2938475',
    location: 'Reykjavik',
    country: 'Iceland',
    responsible_name: 'Olafur',
    responsible_email: 'olafur@gmail.com',
    client_name: 'Sin Xaio Hel',
    transport_type: 'Sea',
    product_type: 'Outdoor Gear',
    last_modify: '05/09/2021',
    created_at: '05/09/2021',
  },
  {
    id: 35,
    reference_number: '7463829',
    location: 'Ljubljana',
    country: 'Slovenia',
    responsible_name: 'Maja',
    responsible_email: 'maja@gmail.com',
    client_name: 'XYZ Corporation',
    transport_type: 'Air',
    product_type: 'Electronics',
    last_modify: '02/05/2022',
    created_at: '02/05/2022',
  },
  {
    id: 36,
    reference_number: '8273641',
    location: 'Vilnius',
    country: 'Lithuania',
    responsible_name: 'Jonas',
    responsible_email: 'jonas@gmail.com',
    client_name: 'ABC Company',
    transport_type: 'Land',
    product_type: 'Beer',
    last_modify: '10/12/2021',
    created_at: '10/12/2021',
  },
  {
    id: 37,
    reference_number: '2938475',
    location: 'Riga',
    country: 'Latvia',
    responsible_name: 'Anna',
    responsible_email: 'anna@gmail.com',
    client_name: 'Sin Xaio Hel',
    transport_type: 'Sea',
    product_type: 'Clothing',
    last_modify: '05/08/2021',
    created_at: '05/08/2021',
  },
  {
    id: 38,
    reference_number: '4657283',
    location: 'Tallinn',
    country: 'Estonia',
    responsible_name: 'Mart',
    responsible_email: 'mart@gmail.com',
    client_name: 'XYZ Corporation',
    transport_type: 'Air',
    product_type: 'Electronics',
    last_modify: '10/11/2021',
    created_at: '10/11/2021',
  }
    ],

    employesListHeaders:['id','legalFirstName','legalMiddleName','legalLastName','email','password','age','Position','View','Action'],
    employesList: [
      {
        id:'4',
        legalFirstName:'Matija',
        legalMiddleName:'Marin',
        legalLastName:'Corak',
        email:'matija@gmail.com',
        password:'*****',
        age:'30-54',
        Position:'Driver',
      },
      {
        id:'5',
        legalFirstName:'Pero',
        legalMiddleName:'Marin',
        legalLastName:'Corak',
        email:'matija@gmail.com',
        password:'*****',
        age:'30-54',
        Position:'Driver',
      },
      {
        id:'6',
        legalFirstName:'Sandro',
        legalMiddleName:'Marin',
        legalLastName:'Corak',
        email:'matija@gmail.com',
        password:'*****',
        age:'30-54',
        Position:'Driver',
      },
      {
        id:'7',
        legalFirstName:'Juro',
        legalMiddleName:'Marin',
        legalLastName:'Corak',
        email:'matija@gmail.com',
        password:'*****',
        age:'30-54',
        Position:'Driver',
      },
     

    ],
      dataItemsHeaders:['name','surname','country','lastModify','url','View','Action'],
      dataItems: [
        {
          name: 'Frozen Yogurt',
          surname: 'Krazy',
          country: 'Croatia',
          lastModify: '15/10/2023',
          url:'/post/Ref34856'
        },
        {
          name: 'Ice cream sandwich',
          surname: 'Frozy',
          country: 'Croatia',
          lastModify: '15/10/2023', 
          url:'/user/1'
        },
        {
          name: 'Eclair',
          surname: 'Frozy',
          country: 'Croatia',
          lastModify: '15/10/2021',
          url:'/post/3'
        },
        {
          name: 'Cupcake',
          surname: 'Frozy',
          country: 'Croatia',
          lastModify: '15/10/2021',
          url:'/post/4'
        },
        {
          name: 'Gingerbread',
          surname: 'Frozy',
          country: 'Croatia',
          lastModify: '15/10/2021',
          url:'/post/5'
        },
        {
          name: 'Jelly bean',
          surname: 'Frozy',
          country: 'Croatia',
          lastModify: '15/10/2021',
          url:'/object/6'
        },
        {
          name: 'Lollipop',
          surname: 'Frozy',
          country: 'Croatia',
          lastModify: '15/10/2021',
          url:'/object/7'
        },
        {
          name: 'Honeycomb',
          surname: 'Frozy',
          country: 'Croatia',
          lastModify: '15/10/2021',
          url:'/object/8'
        },
        {
          name: 'Donut',
          surname: 'Frozy',
          country: 'Croatia',
          lastModify: '15/10/2021',
          url:'/object/9'
        },
        {
          name: 'KitKat',
          surname: 'Frozy',
          country: 'Croatia',
          lastModify: '15/10/2021',
          url:'/object/10'
        },
        {
          name: 'Frozen Yogurt',
          surname: 'Krazy',
          country: 'Croatia',
          lastModify: '15/10/2021',
          url:'/object/Ref34856'
        },
        {
          name: 'Ice cream sandwich',
          surname: 'Frozy',
          country: 'Croatia',
          lastModify: '15/10/2021', 
          url:'/user/1'
        },
        {
          name: 'Eclair',
          surname: 'Frozy',
          country: 'Croatia',
          lastModify: '15/10/2021',
          url:'/object/3'
        },
        {
          name: 'Cupcakssse',
          surname: 'Frozy',
          country: 'Croatia',
          lastModify: '15/10/2021',
          url:'/object/4'
        },
        {
          name: 'Gingerbread',
          surname: 'Frozy',
          country: 'Croatia',
          lastModify: '15/10/2021',
          url:'/object/5'
        },
        {
          name: 'Jelly bean',
          surname: 'Frozy',
          country: 'Croatia',
          lastModify: '15/10/2021',
          url:'/object/6'
        },
        {
          name: 'Lollipop',
          surname: 'Frozy',
          country: 'Croatia',
          lastModify: '15/10/2021',
          url:'/object/7'
        },
        {
          name: 'Honeycomb',
          surname: 'Frozy',
          country: 'Croatia',
          lastModify: '15/10/2021',
          url:'/object/8'
        },
        {
          name: 'Donut',
          surname: 'Frozy',
          country: 'Croatia',
          lastModify: '15/10/2021',
          url:'/object/9'
        },
        {
          name: 'KitKat',
          surname: 'Frozy',
          country: 'Croatia',
          lastModify: '15/10/2021',
          url:'/object/10'
        },
      ],
    }
  },
}
</script>


<style scoped>

</style>